// <auto-generated />
namespace JokerKS.WLFU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BasketTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasketTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803101226570_BasketTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
