// <auto-generated />
namespace JokerKS.WLFU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BidAtAuctions_isWinner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BidAtAuctions_isWinner));
        
        string IMigrationMetadata.Id
        {
            get { return "201803262046343_BidAtAuctions_isWinner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
