// <auto-generated />
namespace JokerKS.WLFU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Auctions_Datestart_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Auctions_Datestart_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201803252022081_Auctions_Datestart_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
