// <auto-generated />
namespace JokerKS.WLFU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tags_Name_isUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tags_Name_isUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251956019_Tags_Name_isUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
