// <auto-generated />
namespace JokerKS.WLFU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Users_IsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Users_IsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221345363_Users_IsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
